// Mirrors tday-web/src/lib/listIcons.ts so widget list icons match the Tday app exactly.
import {
  Activity,
  Archive,
  Baby,
  Backpack,
  Book,
  Bookmark,
  BriefcaseBusiness,
  BriefcaseMedical,
  Building2,
  Cake,
  Calendar,
  Camera,
  Car,
  Check,
  Circle,
  CircleDollarSign,
  Clock,
  Code,
  Droplet,
  Dumbbell,
  FileText,
  Flag,
  Flame,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  Headphones,
  Heart,
  House,
  Inbox,
  Key,
  Landmark,
  Leaf,
  Lightbulb,
  List,
  type LucideIcon,
  MessageCircle,
  Monitor,
  Music,
  Palette,
  PawPrint,
  Pencil,
  Plane,
  Scissors,
  Ship,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smile,
  Snowflake,
  Square,
  Star,
  Sun,
  Train,
  Triangle,
  TriangleAlert,
  Umbrella,
  UsersRound,
  Utensils,
  WalletCards,
  Wine,
} from "lucide-react";

const DEFAULT_LIST_ICON_KEY = "inbox";

const listIconEntries: [string, LucideIcon][] = [
  [DEFAULT_LIST_ICON_KEY, Inbox],
  ["sun", Sun],
  ["calendar", Calendar],
  ["schedule", Clock],
  ["flag", Flag],
  ["check", Check],
  ["smile", Smile],
  ["list", List],
  ["bookmark", Bookmark],
  ["key", Key],
  ["gift", Gift],
  ["cake", Cake],
  ["school", GraduationCap],
  ["bag", Backpack],
  ["edit", Pencil],
  ["document", FileText],
  ["book", Book],
  ["work", BriefcaseBusiness],
  ["wallet", WalletCards],
  ["money", CircleDollarSign],
  ["fitness", Dumbbell],
  ["run", Activity],
  ["food", Utensils],
  ["drink", Wine],
  ["health", BriefcaseMedical],
  ["monitor", Monitor],
  ["music", Music],
  ["computer", Monitor],
  ["game", Gamepad2],
  ["headphones", Headphones],
  ["eco", Leaf],
  ["pets", PawPrint],
  ["child", Baby],
  ["family", UsersRound],
  ["basket", ShoppingBasket],
  ["cart", ShoppingCart],
  ["mall", ShoppingBag],
  ["inventory", Archive],
  ["soccer", Circle],
  ["baseball", Circle],
  ["basketball", Circle],
  ["football", Circle],
  ["tennis", Circle],
  ["train", Train],
  ["flight", Plane],
  ["boat", Ship],
  ["car", Car],
  ["umbrella", Umbrella],
  ["drop", Droplet],
  ["snow", Snowflake],
  ["fire", Flame],
  ["tools", Hammer],
  ["scissors", Scissors],
  ["architecture", Landmark],
  ["code", Code],
  ["idea", Lightbulb],
  ["chat", MessageCircle],
  ["alert", TriangleAlert],
  ["star", Star],
  ["heart", Heart],
  ["circle", Circle],
  ["square", Square],
  ["triangle", Triangle],
  ["home", House],
  ["city", Building2],
  ["bank", Landmark],
  ["camera", Camera],
  ["palette", Palette],
];

const listIconMap = new Map(listIconEntries);

const normalizeListIconKey = (iconKey?: string | null) => {
  const candidate = iconKey?.trim().toLowerCase();
  if (!candidate) return DEFAULT_LIST_ICON_KEY;
  const normalized =
    candidate === "briefcase"
      ? "work"
      : candidate === "cocktail"
        ? "drink"
        : candidate === "travel"
          ? "flight"
          : candidate;
  return listIconMap.has(normalized) ? normalized : DEFAULT_LIST_ICON_KEY;
};

export const getListIcon = (iconKey?: string | null): LucideIcon => listIconMap.get(normalizeListIconKey(iconKey)) ?? Inbox;
